"""empty message

Revision ID: 2580556fa6df
Revises: a02f36060c5
Create Date: 2016-01-06 16:16:38.330848

"""

# revision identifiers, used by Alembic.
revision = '2580556fa6df'
down_revision = 'a02f36060c5'

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solar_panels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('solar_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('area', geoalchemy2.types.Geometry(geometry_type='POLYGON'), nullable=False),
    sa.Column('size', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['solar_id'], ['solar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('solar_panels')
    ### end Alembic commands ###
