"""empty message

Revision ID: 3055bc5d820
Revises: None
Create Date: 2016-01-04 00:51:07.141286

"""

# revision identifiers, used by Alembic.
revision = '3055bc5d820'
down_revision = None

from alembic import op
import sqlalchemy as sa
import geoalchemy2

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('solar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('project_name', sa.String(length=50), nullable=True),
    sa.Column('client_name', sa.String(length=50), nullable=True),
    sa.Column('client_contact_no', sa.String(length=50), nullable=True),
    sa.Column('coordinates', geoalchemy2.types.Geometry(geometry_type='POINT'), nullable=True),
    sa.Column('area', geoalchemy2.types.Geometry(geometry_type='POLYGON'), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('county', sa.String(length=100), nullable=True),
    sa.Column('site_description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('solar_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('solar_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_name', sa.Text(), nullable=True),
    sa.Column('type', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['solar_id'], ['solar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('account_status', sa.Integer(), nullable=True),
    sa.Column('auth_module_name', sa.String(length=100), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('last_login_datetime', sa.DateTime(), nullable=True),
    sa.Column('last_access_datetime', sa.DateTime(), nullable=True),
    sa.Column('account_create_datetime', sa.DateTime(), nullable=True),
    sa.Column('temporary_login_lockout', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('solar_file')
    op.drop_table('solar')
    op.drop_table('role')
    ### end Alembic commands ###
