"""empty message

Revision ID: 41a0891ad6b0
Revises: 309592978114
Create Date: 2016-01-12 19:01:21.102422

"""

# revision identifiers, used by Alembic.
revision = '41a0891ad6b0'
down_revision = '309592978114'

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash', sa.String(), nullable=True))
    op.drop_column('user', 'password')
    op.drop_column('user', 'account_create_datetime')
    op.drop_column('user', 'is_admin')
    op.drop_column('user', 'last_access_datetime')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_access_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('account_create_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('password', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('user', 'password_hash')
    ### end Alembic commands ###
