"""empty message

Revision ID: a02f36060c5
Revises: 3055bc5d820
Create Date: 2016-01-04 21:28:30.306762

"""

# revision identifiers, used by Alembic.
revision = 'a02f36060c5'
down_revision = '3055bc5d820'

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solar', sa.Column('address', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('solar', 'address')
    ### end Alembic commands ###
